name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select default Xamarin bundle to 6_12_6
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2

    - name: Setup .NET Core SDK 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore $GITHUB_WORKSPACE/Todo.sln

    - name: Build
      run: msbuild $GITHUB_WORKSPACE/Todo.Android/Todo.Android.csproj /t:PackageForAndroid /p:Configuration=Debug
