name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select default Xamarin bundle to 6_12_5
      run: |
        XAMARIN_SDK=6_12_5
        $VM_ASSETS/select-xamarin-sdk.sh $XAMARIN_SDK
    
    - name: Set default Xcode 12.3
      run: |
        sudo xcode-select -s /Applications/Xcode_12.3.0.app/Contents/Developer

    - name: Setup .NET Core SDK 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore $GITHUB_WORKSPACE/Todo.sln

    - name: Build
      run: |
        msbuild $GITHUB_WORKSPACE/Todo.iOS/Todo.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
