name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select default Xamarin bundle to 6_10_0
      run: |
        XAMARIN_SDK=6_10_0
        $VM_ASSETS/select-xamarin-sdk.sh $XAMARIN_SDK
    
    - name: Set default Xcode 11.6
      run: |
        XCODE_ROOT=/Applications/Xcode_11.6.0.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT

    - name: Setup .NET Core SDK 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore $GITHUB_WORKSPACE/Todo.sln

    - name: Build
      run: |
        msbuild $GITHUB_WORKSPACE/Todo.iOS/Todo.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
